name: 'Hashibul Hussain Test'
version: '1.0.0'
config-version: 2

profile: 'test-example' # for connection to data warehouse

model-paths: ['models']

models:
    +persist_docs: # for the table and column descriptions to show on DB
        relation: true
        columns: true
    Hashibul Hussain Test:
        example:
            Materialized: view
